# pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6

  provider: ^6.1.2 # Para MVVM e gerenciamento de estado simples
  get_it: ^7.7.0   # Para injeção de dependências
  # Comunicação HTTP
  dio: ^5.4.3+1 # Cliente HTTP robusto
  # Notificações locais
  flutter_local_notifications: ^17.1.2 # Notificações locais
  shared_preferences: ^2.2.3 # Para dados simples e persistência

  form_validator: ^1.0.1 # Para validação de formulários
  intl: ^0.19.0 # Para formatação de datas e internacionalização